version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example

  java:
    build: .
    depends_on:
        - db
    restart: always
    environment:
      - API_KEY=needed
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=example
    ports:
      - 8080:8080
